#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/zathura
ln -s $DOTFILES/zathura $HOME/.config/zathura

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/picom
ln -s $DOTFILES/picom $HOME/.config/picom

rm -rf $HOME/.config/i3
ln -s $DOTFILES/i3 $HOME/.config/i3

rm -rf $HOME/.config/i3status
ln -s $DOTFILES/i3status $HOME/.config/i3status
